### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by BitProcessor** [nerdswords/yet-another-cloudwatch-exporter#371]
On `quay.io/invisionag/yet-another-cloudwatch-exporter:v0.26.3-alpha`
What probably happened was a temporary network failure. 

Caused: `panic: runtime error: invalid memory address or nil pointer dereference`

According to the logs, it seems to recover, but no metrics. 
Stats in Grafana are blank since that moment.

Manual restart fixed the problem.

```
{"level":"info","msg":"Parse config..","time":"2021-04-15T12:54:17Z"}
{"level":"info","msg":"Startup completed","time":"2021-04-15T12:54:17Z"}
{"level":"info","msg":"Couldn't get account Id for role : RequestError: send request failed\ncaused by: Post \"https://sts.amazonaws.com/\": read tcp 172.20.0.5:34492-\u003e54.239.21.217:443: read: connection reset by peer\n","time":"2021-04-16T13:52:44Z"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xe10b9d]

goroutine 7 [running]:
main.createPrometheusLabels(0xc00023bd40, 0xc000e2d8a0)
	/opt/aws_cloudwatch.go:363 +0x11d
main.migrateCloudwatchToPrometheus(0xc000ed0000, 0x600, 0x600, 0x2, 0x0, 0x0)
	/opt/aws_cloudwatch.go:512 +0x408
main.updateMetrics(0xc0008ca050, 0x0, 0xed80b8d08, 0x1a13760, 0x2, 0x1a13760, 0xa4d7dac4)
	/opt/main.go:51 +0xe6
main.main.func1(0xc0002c86e0, 0xc00000e3c0, 0xc000025f80)
	/opt/main.go:118 +0xfa
created by main.main
	/opt/main.go:114 +0x5ec
{"level":"info","msg":"Parse config..","time":"2021-04-16T13:52:49Z"}
{"level":"info","msg":"Startup completed","time":"2021-04-16T13:52:49Z"}
```

**Comment by cristiangreco** [comment]
Closing this as it seems to refer to a really old version of yace. If you can still reproduce the issue with the latest realease please feel free to reopen.
