### ISSUE TITLE
how can get msk's metrics

### ISSUE THREAD

**Issue by Jacksonary** [nerdswords/yet-another-cloudwatch-exporter#549]
does this exporter support msk's metrics? I configured it as follows: 

```yaml
  - type: kafka
    regions:
      - eu-west-1
    searchTags:
      - key: env
        value: dev
    metrics:
      - name: MemoryFree
        statistics:
        - Average
        period: 30
        length: 600
``

but I has not found kafka's metrics, what can I do with it? thinks!

**Comment by Jacksonary** [comment]
and pod can not start, log as follows

```log
{"level":"info","msg":"Parse config..","time":"2022-03-25T06:51:14Z"}
{"level":"info","msg":"Startup completed","time":"2022-03-25T06:51:14Z"}
panic: assignment to entry in nil map
goroutine 126 [running]:
main.getFilteredMetricDatas(0xc0000c45b0, 0xa, 0xc000606328, 0xc0000c4590, 0x5, 0x0, 0x0, 0x0, 0xc0000a04e0, 0x1a109e0, ...)
	/opt/aws_cloudwatch.go:312 +0x2fc
main.getMetricDataForQueries(0xc0000fc2c0, 0xc000254540, 0xc0000c45b0, 0xa, 0xc000606328, 0xc0000a04e0, 0x134b0c0, 0xc000636068, 0xc00000e058, 0x1, ...)
	/opt/abstract.go:179 +0x2a5
main.scrapeDiscoveryJobUsingMetricData(0xc0000fc2c0, 0xc0000c45b0, 0xa, 0xc000606328, 0xc0000a04e0, 0x13483c0, 0xc000636098, 0x134b820, 0xc000636148, 0x134be40, ...)
	/opt/abstract.go:202 +0x233
main.scrapeAwsData.func1(0xc000384010, 0xc0000a04e0, 0xc0000a05a0, 0x5, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/opt/abstract.go:51 +0x329
created by main.scrapeAwsData
	/opt/abstract.go:37 +0x3f0
```
